name: Deprem DB Sync
permissions:
  contents: write


on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # 15 dakikada bir

permissions:
  contents: write   # commit/push için şart

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu cek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Kutuphaneleri kur
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
              - name: Telegram TEST (curl)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "ChatID=$TELEGRAM_CHAT_ID"
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=✅ GitHub Actions test mesajı (Deprem DB Sync) çalıştı."
        

      - name: Deprem scriptini calistir
        run: |
          python main.py

      - name: DB degisti mi? commit+push
  	    run: |
    	  git config user.name "github-actions[bot]"
    	  git config user.email "github-actions[bot]@users.noreply.github.com"

    	  if git status --porcelain | grep .; then
      	    git add deprem.db
      	    git commit -m "deprem.db guncellendi"
      	    git push
    	  else
            echo "DB degismemis, push yok."
    	 fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "deprem.db guncellendi"
          git push
